// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellora.InventoryService.Infrastructure.Persistence;

#nullable disable

namespace Sellora.InventoryService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260922060044_AddInventoryOutbox")]
    partial class AddInventoryOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.InventoryOwner", b =>
                {
                    b.Property<Guid>("InventoryOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_owner_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("ExternalOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_owner_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_type");

                    b.HasKey("InventoryOwnerId")
                        .HasName("pk_inventory_owner");

                    b.HasIndex("CompanyId", "OwnerType", "ExternalOwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_inventory_owner_company_type_external_owner");

                    b.ToTable("inventory_owner", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_owner_type", "owner_type IN ('Company', 'Agency', 'SalesRep')");
                        });
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.ProcessedInventoryEvent", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("CompanyId", "EventId");

                    b.ToTable("processed_inventory_event", (string)null);
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("InventoryOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_owner_id");

                    b.Property<bool>("LowStockNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("low_stock_notified");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_reserved");

                    b.Property<int?>("ReorderThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_threshold");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("StockItemId")
                        .HasName("pk_stock_item");

                    b.HasIndex("InventoryOwnerId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_item_owner_product_without_batch")
                        .HasFilter("\"batch_id\" IS NULL");

                    b.HasIndex("InventoryOwnerId", "ProductId", "BatchId")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_item_owner_product_batch")
                        .HasFilter("\"batch_id\" IS NOT NULL");

                    b.ToTable("stock_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_item_on_hand_non_negative", "quantity_on_hand >= 0");

                            t.HasCheckConstraint("ck_stock_item_reserved_non_negative", "quantity_reserved >= 0");

                            t.HasCheckConstraint("ck_stock_item_reserved_not_above_on_hand", "quantity_reserved <= quantity_on_hand");
                        });
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("StockMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_movement_id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor_id");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("movement_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("OnHandDelta")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand_delta");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reference_type");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<int>("ReservedDelta")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_delta");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.HasKey("StockMovementId")
                        .HasName("pk_stock_movement");

                    b.HasIndex("StockItemId", "OccurredAt")
                        .HasDatabaseName("ix_stock_movement_stock_item_occurred_at");

                    b.ToTable("stock_movement", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movement_type", "movement_type IN ('Adjustment', 'Reserved', 'Released', 'Sold', 'Returned', 'Transferred')");
                        });
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockReservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InventoryOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_owner_id");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("ReservationId")
                        .HasName("pk_stock_reservation");

                    b.HasIndex("InventoryOwnerId");

                    b.HasIndex("CompanyId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_reservation_company_order_reference");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_stock_reservation_status_expires_at");

                    b.ToTable("stock_reservation", (string)null);
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockReservationLine", b =>
                {
                    b.Property<Guid>("StockReservationLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_reservation_line_id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.HasKey("StockReservationLineId")
                        .HasName("pk_stock_reservation_line");

                    b.HasIndex("StockItemId");

                    b.HasIndex("ReservationId", "StockItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_reservation_line_reservation_stock_item");

                    b.ToTable("stock_reservation_line", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_reservation_line_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("Sellora.InventoryService.Domain.Entities.InventoryOwner", "InventoryOwner")
                        .WithMany("StockItems")
                        .HasForeignKey("InventoryOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_item_inventory_owner");

                    b.Navigation("InventoryOwner");
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Sellora.InventoryService.Domain.Entities.StockItem", "StockItem")
                        .WithMany("Movements")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_stock_item");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockReservation", b =>
                {
                    b.HasOne("Sellora.InventoryService.Domain.Entities.InventoryOwner", null)
                        .WithMany()
                        .HasForeignKey("InventoryOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservation_inventory_owner");
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockReservationLine", b =>
                {
                    b.HasOne("Sellora.InventoryService.Domain.Entities.StockReservation", "Reservation")
                        .WithMany("Lines")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sellora.InventoryService.Domain.Entities.StockItem", null)
                        .WithMany()
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_reservation_line_stock_item");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.InventoryOwner", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockItem", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Sellora.InventoryService.Domain.Entities.StockReservation", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
